### ISSUE TITLE
2 Bugs I Have Found

### ISSUE THREAD

**Issue by IPickedARandomUsername** [ultratype/UltraTypeBot#3] opened 2017-11-07 15:50 UTC
I have encountered 2 bugs.  The first one is the Auto Refresh sometimes leads to a infinite loading screen that never loads.  The second bug is the WPM and Accuracy every couple races or so will change then after that race is done is changes back to my settings. For an example I have my settings at 98% Accuracy and WPM at 65,  it will change from those settings to a random one like 106 WPM and 80% Accuracy.

**Comment by ultratype** [comment] 2017-11-09 03:49
Regarding the auto refresh "infinite loop" – this is usually caused by a poor network connection. This can usually be fixed by running UltraType on a more stable network. Regarding the WPM fluctuations, I will look into the issue and get back to you on it. Thank you for taking the time to report these.

**Comment by ultratype** [comment] 2017-11-10 03:45
I've fixed the WPM issue and a new version of the extension will roll out with this bug fixed within the next few minutes.

**Closed as completed by ultratype** 2017-11-10 03:45 UTC

**Comment by IPickedARandomUsername** [comment] 2017-11-13 06:26
Thanks Bro!
